### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by zidanefst** [ValentinMitran/FreelancersGuardian#1]
Hey,

I came across an idea. What if you make the landing page modular?
By doing that, you would facilitate third party development for themes and plugins

Thanks

**Comment by ValentinMitran** [comment]
Hello @zidanefst ,

Haven't thought about that, but it seems like a good idea.
So, you're suggesting something like Wordpress does where you can upload themes and plugins to enhance the experience, right?

**Comment by zidanefst** [comment]
Yeah yeah

Exactly like WordPress. Customization is a big thing in these kind of platforms. After all, that's what made WordPress the king of CMS.

So think about it. Do you want to be just another random platform or do you want to be a whole ecosystem?

**Comment by ValentinMitran** [comment]
> Do you want to be just another random platform or do you want to be a whole ecosystem?

Touché. That's a fair point. I'll add that to the backlog.
Thanks for the idea, if you have more requests or improvement tips, feel free to open other issues.

Thanks for supporting the project!
